apiVersion: v1
kind: Service 

metadata:
  name: wordpress-mysql
  namespace: efs
  labels:
    app: wordpress 
spec: 
  ports: 
  - port: 3306 
selector:
  app: wordpress 
  tier: backend 
clusterIP: None 

--- 

apiVersion: apps/v1 
kind: Deployment

metadata:
  name: wordpress-mysql 
  namespace: efs
spec:
  selector:
    matchLabels:
      app: wordpress-mysql  
      tier: backend
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql 
    spec:
      containers:
      - name: mysql
        image: mysql:5.8
        env: 
        - name: MYSQL_ROOT_PASSWORD 
        valueFrom: 
          secretKeyRef: 
            name: mysql-pass
            key: password
        ports:
        - containerPort: 3306
          name: mysql 
        volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql 
        volumes:
        - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: efs-mysql 

