apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding

metadata:
  name: nfs-provisioner-role-binding
subjects:
  - kind: ServiceAccount
    name: efs-provisioner
    namespace: efs
roleRef:
  kind: ClusterRole 
  name: k8s-clusteradmin-1 
  apiGroup: rbac.authorization.k8s.io
