apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding

metadata:
  name: nfs-provisioner-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: efs
roleRef:
  kind: ClusterRole 
  name: k8s-clusteradmin-1 #STILL IN PROGRESS
  apiGroup: rbac.authorization.k8s.io