apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mysql-pvc
  namespace: stateful
  labels:
    app: wordpress 
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 20Gi

--- 

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: wordpress-pvc
  namespace: stateful 
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi 