kind: StorageClass
apiVersion: storage.k8s.io/v1

metadata:
  name: stateful-sc
  namespace: stateful
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
mountOptions:
  - debug  