apiVersion: v1
kind: Service

metadata:
  name: frontend
  namespace: stateless
  labels:
    app: guestbook
    tier: frontend
spec:
  selector:
    app: guestbook
    tier: frontend
  type: LoadBalancer
  ports:
  - port: 80