apiVersion: apps/v1 
kind: Deployment

metadata:
  name: redis-slave
  namespace: stateless 
spec:
  selector:
    matchLabels:
      app: redis
      role: slave  
      tier: backend 
  replicas: 2 
  template:
    metadata:
      labels:
        app: redis 
        role: slave
        tier: backend  
    spec:
      containers:  
      - name: agent 
        image: gcr.io/google_samples/gb-redisslave:v1 
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
        env: 
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 6379
